[ENG-1966] fix: ensure github action fails in case of linter errors

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -13,5 +13,9 @@ jobs:
       run: yarn
     - name: Run linter
       run: yarn lint:dry
+      # If linting fails, the workflow will stop here
     - name: Build project
-      run: yarn build
+      run: |
+        set -e  # Exit immediately if a command exits with a non-zero status
+        yarn build
+      # This ensures that if the build fails, the GitHub Action will also fail
