[ENG-1966] fix: ensure github action fails in case of linter errors (#920)

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -14,4 +14,7 @@ jobs:
     - name: Run linter
       run: yarn lint:dry
     - name: Build project
-      run: yarn build
+      run: |
+        set -e  # Exit immediately if a command exits with a non-zero status
+        yarn build
+      # This ensures that if the build fails, the GitHub Action will also fail
